### 

POST http://localhost:5193/todoitems
content-type: application/json

{
    "id": 1,
    "Name": "ptnminh",
    "IsComplete": true
}


### 
POST http://localhost:3000/greet/sayHello
content-type: application/json

{
   "name": "ptnminh"
}